comment: false
coverage:
  status:
    # overall project coverage is not super useful, just report patch coverage
    project:
      default: false
    patch:
      default:
        target: 70% # reasonable goal for now

ignore:
  - "**/*mock*.go" # ignore go interface mock implementations
